<?php

use Drupal\Core\Form\FormStateInterface;
use \Drupal\Component\Utility\NestedArray;

/**
 * Implements hook_element_info_alter().
 */
function files_undo_remove_element_info_alter(&$types) {
  if (isset($types['managed_file'])) {
    $types['managed_file']['#process'][] = 'files_undo_remove_element_process';
    $types['managed_file']['#attached']['library'][] = 'files_undo_remove/files_undo_remove.undo';
  }
}

function files_undo_remove_element_process(array $element, FormStateInterface $form_state, array &$form) {
  // Do not process on field edit form.
  if ($form['#form_id'] == 'field_config_edit_form' || $form['#form_id'] == 'field_storage_config_edit_form') {
    return $element;
  }
  if ($element['#cardinality'] == 1) {
      return $element;
  }
  // Change the remove button to one of ours.
    $element['remove_button'] = array(
      '#name' => $element['remove_button']['#name'],
      '#type' => 'submit',
      '#value' => t('Remove'),
      '#attributes' => array(
        'class' => array('files-undo-remove'),
      ),
      '#weight' => -5,
    );
   $values = NestedArray::getValue($form_state->getValues(), $element['#parents']);
    // $remove_state = isset($values['remove_state']) ? $values['remove_state'] : 0;
  kint($form_state->getValues());
  kint($values);
    $element['remove_state'] = array(
      '#type' => 'hidden',
      '#default_value' => 0,
      '#attributes' => array('class' => array('files-undo-remove-hidden-state')),
    );
  return $element;
}
